name: Run Shell Script

on:
  workflow_dispatch:
    inputs:
      env:
        description: AWS Environment
        type: choice
        required: true
        options:
          - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run shell script
        run: |
          pwd
          chmod target/classes/script.sh
          ./target/classes/script.sh

